// Colors

export default {
	PRIMARY_COLOR: "#F5AA00",
	PRIMARY_LIGHT_COLOR: "#F06B43",
	SECONDARY_COLOR: "#FFF7E8",
	BACKGROUND_COLOR: "#EBEBEB",
	BACKGROUND_WHITE: "white",
	BACKGROUND_GRAY:"#d9dde2",
	TEXTCOLOR_BLACK: "#000000",
	TEXTCOLOR_DARKGREY: "#808080",
	TEXTCOLOR_GREEN: "#04C424"
};
