export const EditProfileActionTypes = {
    // get basic info from backend
    EDIT_USER_BASIC_INFO_START:"EDIT_USER_BASIC_INFO_START",
    EDIT_USER_BASIC_INFO_SUCCESS:"EDIT_USER_BASIC_INFO_SUCCESS",
    EDIT_USER_BASIC_INFO_FAIL:"EDIT_USER_BASIC_INFO_FAIL",

    EDIT_USER_INFO_CHANGED:"EDIT_USER_INFO_CHANGED",   

    BASIC_INFO_SUBMIT_START:"BASIC_INFO_SUBMIT_START",
    BASIC_INFO_SUBMIT_SUCCESS:"BASIC_INFO_SUBMIT_SUCCESS",
    BASIC_INFO_SUBMIT_FAIL:"BASIC_INFO_SUBMIT_FAIL",

    LOCATION_INFO_SUBMIT_START:"LOCATION_INFO_SUBMIT_START",
    LOCATION_INFO_SUBMIT_SUCCESS:"LOCATION_INFO_SUBMIT_SUCCESS",
    LOCATION_INFO_SUBMIT_FAIL:"LOCATION_INFO_SUBMIT_FAIL",

    SOCIAL_INFO_SUBMIT_START:"SOCIAL_INFO_SUBMIT_START",
    SOCIAL_INFO_SUBMIT_SUCCESS:"SOCIAL_INFO_SUBMIT_SUCCESS",
    SOCIAL_INFO_SUBMIT_FAIL:"SOCIAL_INFO_SUBMIT_FAIL",

    CHANGE_PASSWORD_SUBMIT_START:"CHANGE_PASSWORD_SUBMIT_START",
    CHANGE_PASSWORD_SUBMIT_SUCCESS:"CHANGE_PASSWORD_SUBMIT_SUCCESS",
    CHANGE_PASSWORD_SUBMIT_FAIL:"CHANGE_PASSWORD_SUBMIT_FAIL"



};
