export const EditProfileActionTypes = {
    // get basic info from backend
    EDIT_USER_BASIC_INFO_START:"EDIT_USER_BASIC_INFO_START",
    EDIT_USER_BASIC_INFO_SUCCESS:"EDIT_USER_BASIC_INFO_SUCCESS",
    EDIT_USER_BASIC_INFO_FAIL:"EDIT_USER_BASIC_INFO_FAIL",

    EDIT_USER_NAME_CHANGED:"EDIT_USER_NAME_CHANGED",
    EDIT_USER_COUNTRY_CODE_CHANGED:"EDIT_USER_COUNTRY_CODE_CHANGED",
    EDIT_USER_EMAIL_CHANGED:"EDIT_USER_EMAIL_CHANGED",
    EDIT_USER_PHONE_CHANGED:"EDIT_USER_PHONE_CHANGED",

    BASIC_INFO_SUBMIT_START:"BASIC_INFO_SUBMIT_START",
    BASIC_INFO_SUBMIT_SUCCESS:"BASIC_INFO_SUBMIT_SUCCESS",
    BASIC_INFO_SUBMIT_FAIL:"BASIC_INFO_SUBMIT_FAIL"


};
